library(shinydashboard)
library(shiny)
library(jsonlite)
library(dplyr)
library(readxl)
library(dipsaus)
library(shinyWidgets)
library(DT)
library(jsonlite)
library(dplyr)
library(fs)
library(shinyalert)
library(shinyjs)
library(rlang)
library(httr)
source(file = 'paramConfig.R')      #  Carrega os paramentros globais

