
library(dplyr)
library(readxl)
library(dipsaus)
library(shinyWidgets)
library(DT)
library(jsonlite)
library(dplyr)
library(fs)
library(shinyalert)
library(shinyjs)
library(rlang)
library(googledrive)

rsconnect::deployApp(appDir = getwd())
token <- drive_auth(path = ".secrets/dhis2-216408-da1e56ebc18b.json" )
